"""empty message

Revision ID: 9809a8b959dd
Revises: 9d2da6ea6d7d
Create Date: 2020-08-28 11:26:17.872258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9809a8b959dd'
down_revision = '9d2da6ea6d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibo', sa.Column('n_like', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weibo', 'n_like')
    # ### end Alembic commands ###
